<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BACKEND_INDEX_TITLE' => 'Blogs language list',
    'BACKEND_INDEX_SUBTITLE' => 'Blogs language list',
    'BACKEND_CREATE_TITLE' => 'BlogsLang',
    'BACKEND_CREATE_SUBTITLE' => 'BlogsLang create',
    'BACKEND_UPDATE_TITLE' => 'BlogsLang',
    'BACKEND_UPDATE_SUBTITLE' => 'BlogsLang update',
    'BACKEND_CANCEL_BTN_TITLE' => 'Cancel',
    'BACKEND_CREATE_SUBMIT' => 'Save',
    'BACKEND_UPDATE_SUBMIT' => 'Update',
];
